<?php
/*********************/
/*                   */
/*  Dezend for PHP5  */
/*         NWS       */
/*      Nulled\.WS    */
/*                   */
/*********************/

periksaroot( );
$help_koreksikurikulum = "Fasilitas ini digunakan untuk melihat data Kurikulum Mata Kuliah yang berpotensi tidak valid saat dikonversi ke DIKTI\. \r\n\r\n  Pemeriksaan dilakukan berdasarkan data referensi yang ada di tabel TBPST (referensi Program Studi)\. Data Kurikulum yang Program Studi-nya tidak terdaftar di TBPST  akan dianggap tidak valid\.\r\n\r\n  Silakan periksa keterangan dari daftar Kurikulum yang tampil dan lakukan penghapusan data jika data Kurikulum tsb benar2 tidak valid dan tidak diperlukan sama sekali";
$help_koreksidosenpengajar = "Fasilitas ini digunakan untuk melihat data Dosen Pengajar yang berpotensi tidak valid saat dikonversi ke DIKTI\. \r\n\r\n  Pemeriksaan dilakukan berdasarkan data referensi yang ada di tabel TBPST (referensi Program Studi), MSDOS (Master Data Dosen) dan TBDOS (Referensi Data Dosen)\. Data Dosen Pengajar yang tidak terdaftar di TBPST, MSDOS dan TBDOS, akan dianggap tidak valid\.\r\n\r\n  Silakan periksa keterangan dari daftar Dosen Pengajar yang tampil dan lakukan penghapusan data jika data Dosen tsb benar2 tidak valid dan tidak diperlukan sama sekali";
$help_koreksikrs = "Fasilitas ini digunakan untuk melihat data KRS Mahasiswa yang berpotensi tidak valid saat dikonversi ke DIKTI\. \r\n \r\n   Pemeriksaan dilakukan berdasarkan data referensi yang ada di tabel TBPST (referensi Program Studi), dan TBKMK (Referensi Data Kurikulum)\. Data KRS Mahasiswa yang tidak terdaftar di TBPST dan TBKMK, akan dianggap tidak valid\.\r\n\r\n  Silakan periksa keterangan dari daftar KRS Mahasiswa yang tampil dan lakukan penghapusan data jika data Dosen tsb benar2 tidak valid dan tidak diperlukan sama sekali\.\r\n  \r\n  <b>Perhatian</b>, karena besarnya data KRS, proses pengecekan mungkin akan memakan waktu yang relatif lama\. Harap bersabar dan jangan tutup program ini selama proses sedang dilakukan\.\r\n  ";
$arrayhelp[tambahmakul] = "\r\nFasilitas ini digunakan untuk entri Data Mata Kuliah \r\n\r\n1\. <b>Jurusan/Program Studi</b> \: pilih Jurusan/Program Studi Mata Kuliah ;\r\n2\. <b>Kode Mata Kuliah</b> \: diisi kode mata kuliah yang digunakan di masing-masing PT\. Tidak boleh mengandung “spasi”, “-”, “\.”, atau “/”;\r\n3\. <b>Nama Mata Kuliah</b> \: diisi nama mata kuliah yang digunakan di masing-masing PT;\r\n4\. <b>Keterangan</b> \: gunakan bila perlu;\r\n5\. <b>Semester</b> \: diisi semester penempatan mata kuliah;\r\n6\. <b>Jenis</b> \: diisi dari pilihan yang ada;\r\n7\. <b>Nama Mata Kuliah di Kurikulum</b> \: diisi nama mata kuliah yang digunakan di masing-masing PT;\r\n8\. <b>Tahun Semester Pelaporan Data</b> \: diisi tahun dan semester pelaporan data;\r\n9\. <b>Jenjang Program Studi</b> \: diisi dari pilihan yang ada;\r\n10\. <b>Program Studi</b> \: diisi program studi mata kuliah (gunakan pop up daftar Referensi Program Studi untuk membantu mencari program studi yang ada pada MSPST);\r\n11\. <b>SKS Kurikulum</b> \: diisi dengan sks mata kuliah sesuai dengan kurikulum;\r\n12\. <b>SKS Tatap Muka</b> \: diisi dengan sks tatap muka (lihat catatan);\r\n13\. <b>SKS Praktikum</b> \: diisi dengan sks praktikum (lihat catatan);\r\n14\. <b>SKS Praktek Lapangan</b> \: diisi dengan sks praktek lapangan (lihat catatan);\r\n15\. <b>Penempatan di Semester</b> \: diisi semester penenmpatan mata kuliah;\r\n16\. <b>Kelompok Mata Kuliah</b> \: diisi dari pilihan yang ada;\r\n17\. <b>Kurikulum Inti/Institusi</b> \: diisi dari pilihan yang ada;\r\n18\. <b>Mata Kuliah Wajib/Pilihan</b> \: diisi dari pilihan yang ada;\r\n19\. <b>No\. Dosen Pengampu</b> \: diisi NIDN dosen pengampu/pengajar mata kuliah (gunakan pop up daftar Referensi Dosen untuk membantu mencari NIDN dosen yang ada pada MSDOS); \r\n20\. <b>Jenjang Program Studi Pengampu</b> \: diisi dari pilihan yang ada;\r\n21\. <b>Program Studi Pengampu</b> \: diisi program studi dosen pengajar (gunakan pop up daftar Referensi Program Studi untuk membantu mencari program studi yang ada pada MSPST);\r\n22\. <b>Status Mata Kuliah</b> \: diisi dari pilihan yang ada\. Status hapus artinya mata kuliah ini sudah tidak dipakai/dihapus/dibuang dari kurikulum terhitung mulai semester pelaporan\. Mata kuliah yang tidak ditawarkan pada salah satu semester, ganjil atau genap, TETAP berstatus aktif;\r\n23\. <b>Silabus</b> \: diisi dari pilihan yang ada\:\r\n24\. <b>Satuan Acara Perkuliahan</b> \: diisi dari pilihan yang ada;\r\n25\. <b>Bahan Ajar</b> \: diisi dari pilihan yang ada;\r\n26\. <b>Diktat</b> \: diisi dari pilihan yang ada;\r\n\r\nCATATAN \:\r\nPenentuan bobot sks pada masing-masing PT bisa sangat bervariasi tergantung pada kebijakan di PT ybs\. Dengan demikian, jumlah sks mata kuliah tidak selalu merupakan penjumlahan dari sks tatap muka + sks praktikum + sks praktek lapang\.";
$arrayhelp[carimakul] = "\r\nFasilitas ini digunakan untuk lihat, cari, update, hapus dan cetak Data Mata Kuliah\. Pencarian dapat menggunakan filter yang ada untuk proses pencarian yang lebih spesifik\. \r\n\r\n<b>Tampilkan</b> \: proses pencarian \r\n";
$arrayhelp[hasilmakul] = "\r\nFasilitas ini digunakan untuk update, hapus dan cetak Data Mata Kuliah\.\r\n\r\n<b>Tampilkan semua</b> \: untuk menampilkan semua Data Mata Kuliah hasil pencarian\r\n<b>Tampilkan per halaman</b> \: untuk menampilkan Data Mata Kuliah hasil pencarian per halaman\r\n\r\n<b>Cetak</b> \: untuk proses cetak Data Mata Kuliah hasil pencarian\r\n".IKONHAPUS." \: hapus Data Mata Kuliah\r\n".IKONUPDATE." \: update Data Mata Kuliah\r\n\r\n";
$arrayhelp[updatemakul] = "\r\nFasilitas ini digunakan untuk edit dan update Data Master Mata Kuliah dan Data DIKTI/Kurikulum (Laporan per Semester)\.\r\n\r\n<b>Update</b> \: untuk proses update dan simpan hasil edit data \r\n<b>Reset</b> \: reset\r\n";
$arrayhelp[tambahdikti] = "\r\nFasilitas ini digunakan untuk menambahkan kurikulum baru mata kuliah ybs\.";
$arrayhelp[updatedikti] = "\r\n<b>Simpan</b> \: untuk proses simpan hasil edit data \r\n<b>Reset</b> \: reset\r\n";
//$arrayhelp .= updatedikti;
$arrayhelp[syaratdikti] = "\r\nFasilitas ini digunakan untuk pengaturan Syarat Pengambilan Mata Kuliah ybs\.\r\n1\.<b>ID Mata Kuliah yang harus diambil</b> \: diisi ID mata kuliah yang harus sudah diambil apabila akan mengambil mata kuliah ybs;\r\n2\.<b>Nilai Minimum Mata Kuliah</b> \: diisi nilai minimal pada mata kuliah yang harus diambil;\r\n3\.<b>Bobot Minimum Mata Kuliah</b> \\: diisi bobot minimal pada mata kuliah yang harus diambil;\r\n4\.<b>Logic</b> \: diisi berdasarkan pilihan yang ada\.\r\n";
$arrayhelp[copydikti] = "\r\nFasilitas ini digunakan untuk salin data atau copy kurikulum mata kuliah\.\r\n\r\n<b>Salin Data !</b> \: untuk proses copy atau salin data kurikulum mata kuliah\r\n\r\n";
$arrayhelp[carikurikulum] = "\r\nFasilitas ini digunakan untuk update, hapus dan cetak Data Kurikulum Mata Kuliah\.\r\n\r\n<b>Tampilkan semua</b> \: untuk menampilkan semua Data Kurikulum Mata Kuliah hasil pencarian\r\n<b>Tampilkan per halaman</b> \: untuk menampilkan Data Kurikulum Mata Kuliah hasil pencarian per halaman\r\n\r\n<b>Cetak</b> \: untuk proses cetak Data Kurikulum Mata Kuliah hasil pencarian\r\n".IKONHAPUS." \: hapus Data Kurikulum Mata Kuliah\r\n".IKONUPDATE." \: update Data Kurikulum Mata Kuliah\r\n";
?>
