<?php
/*********************/
/*                   */
/*  Dezend for PHP5  */
/*         NWS       */
/*      Nulled.WS    */
/*                   */
/*********************/

$headerkhs .= " \r\n\t\t\t \r\n\t\t\t\t<center> \r\n\t\t\t<table   width=660 >\r\n\t\t\t\t<tr valign=top>\r\n\t\t\t\t<td width=60%  class='loseborder' valign=top >\r\n\r\n\t\t\t\t<table    > \r\n \t\t\t\t\t<tr align=left>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>Fakultas</td>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>: ".$arrayfakultas[$d[IDFAKULTAS]]."&nbsp;</td>\r\n\t\t\t\t\t</tr> \r\n\t\t\t\t\t<tr align=left>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>Jurusan</td>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>: ".$arraydepartemen[$d[IDDEPARTEMEN]]."&nbsp;</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr align=left valign=top>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>Program Studi</td>\r\n\t\t\t\t\t\t<td class='loseborder' nowrap valign=top>: ".$arrayprodi[$d[IDPRODI]]."  </td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr align=left valign=top>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>Jenjang</td>\r\n\t\t\t\t\t\t<td class='loseborder' nowrap valign=top>:  ".$arrayjenjang[$d[TINGKAT]]." </td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</table>\t\t\t\t\r\n\r\n\r\n\t\t\t</td>\r\n\t\t\t<td  width=40% class='loseborder' valign=top>\r\n\r\n\t\t\t\t<table    >\r\n\t\t\t\t\t<tr align=left>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>Nama </td>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>: {$d['NAMA']}&nbsp;</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr align=left class='loseborder' >\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>NIM</td>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>: {$d['ID']}&nbsp;</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr align=left>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top> Semester</td>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>: \r\n            \r\n          {$semesterhitung} {$kurawal} ".$arraysemester[$semester]." {$kurakhir}   \r\n            &nbsp;</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr align=left>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top> Tahun Akademik</td>\r\n\t\t\t\t\t\t<td class='loseborder' valign=top>: \r\n            \r\n           ".( $tahun - 1 )."/{$tahun} ".$arraysemester[$semester]."  \r\n            &nbsp;</td>\r\n\t\t\t\t\t</tr> \t\t\t\t</table>\r\n\t\t\t\t\r\n\t\t\t</td>\r\n\t\t</table>\r\n\t\t\r\n\t \r\n\t\t\t";
?>
