<?php
/*********************/
/*                   */
/*  Dezend for PHP5  */
/*         NWS       */
/*      Nulled.WS    */
/*                   */
/*********************/

echo "<s";
echo "tyle type=\"text/css\">\r\n.text {text-transform:capitalize;font-family: Monotype Corsiva;} \r\n</style>\r\n";
$bodyijazah .= "\r\n    <center   style='page-break-after:always;'> \r\n    <table width=1000  >\r\n    <tr>\r\n      <td align=left valign=top class=loseborder style='font-size:14px;'>\r\n      Nomor Seri Ijazah : {$noseriijazah}\r\n      <br><br><br><br><br><br><br><br><br><br><br>\r\n      \r\n      </td>\r\n    </tr>\r\n    <tr >\r\n    <td align=center  class=loseborder >\r\n      <b><i style='font-family: Times New Roman;font-size:14pt;'>dengan ini menyatakan bahwa: </i></b>\r\n      <br><br>\r\n    </td>\r\n    </tr>\r\n    <tr>\r\n    <td align=center style=' font-size:12pt;' class=loseborder>\r\n      <font style='font-family: Monotype Corsiva  ;font-size:28pt; font-weight:bold;'>\r\n      {$d['NAMA']}</font><br><br>\r\n      <b><i style='font-family:Times New Roman'>NPM : {$d['ID']}</i></b> <br><br>\r\n        <font style='font-family: Monotype Corsiva  ;font-size:17pt;'>\r\n      lahir di {$d['TEMPAT']} tanggal {$tmp['2']} ".$arraybulan[$tmp[1] - 1]." {$tmp['0']} \r\n      telah menyelesaikan dengan baik dan memenuhi segala<br> syarat\r\n      pendidikan pada Program Studi {$d['NAMAP']}  \r\n      Fakultas <font class='text'>".strtolower( $d[NAMAF] )."</font> <br>\r\n      <!-- Status terakreditasi nomor {$d['NOMBAMSPST']} <br>-->\r\n      Oleh sebab itu kepadanya diberikan gelar <br><br>\r\n      </b>\r\n      <font style='font-family: Monotype Corsiva  ;font-size:26pt; font-weight:bold;'>\r\n      {$d['GELAR']}\r\n      </font>\r\n       <font style='font-family: Monotype Corsiva  ;font-size:17pt;'>\r\n      <br><br>\r\n      beserta segala hak dan kewajiban yang melekat pada gelar tersebut.\r\n      <br>\r\n      Tanggal kelulusan  {$tgllulus} ".$arraybulan[$blnlulus - 1]." {$thnlulus}\r\n    </td>\r\n    </tr>\r\n    </table>\r\n    <br><br>\r\n    <table width=820>\r\n      <tr valign=top>\r\n        <td width=30% class=loseborder>\r\n        <i style='font-size:14px;'>\r\n          <br><font style='margin-left:16px;font-family: Monotype Corsiva;font-size:19px;'>Dekan,</font>\r\n          <br><br><br><br><br><br>\r\n          <font style='font-size:22px; font-weight:bold;font-family: Monotype Corsiva'>{$d['DEKAN']}</font><br>\r\n          {$d['NIPDEKAN']}\r\n        </td>\r\n        <td  class=loseborder width='40%'>\r\n        {$d['FOTO']}\r\n        </td>\r\n        <td width=30% class=loseborder><font style='position:relative; right:-55px; font-style:14px;'>\r\n          ".$lokasikantor.", {$tgllap['tgl']} ".$arraybulan[$tgllap[bln] - 1]." {$tgllap['thn']}, <br>\r\n          <i style='font-size:14px;'>\r\n\t\t  <font style='margin-left:45px;font-family: Monotype Corsiva;font-size:19px;'>\r\n          Rektor,</font>\r\n          <br><br><br><br><br><br>\r\n          <font style='font-size:22px; font-weight:bold;font-family: Monotype Corsiva'>{$d2['REKTOR']}</font><br>\r\n          {$d2['NIPREKTOR']}\r\n\t\t  </font>\r\n        </td>\r\n      </tr>\r\n    </table>\r\n    </center>\r\n    <br><br>\r\n    ";
?>
