<?php
/*********************/
/*                   */
/*  Dezend for PHP5  */
/*         NWS       */
/*      Nulled.WS    */
/*                   */
/*********************/

periksaroot( );
$arrayhelp[yayasan] = "\r\nFasilitas ini digunakan untuk entri Data Badan Hukum\r\n\r\n1.<b>Kode Badan Hukum</b> : diisi dengan Kode Badan Hukum. Kode Badan Hukum adalah Kode PT ditambah angka 1 didepannya;\r\n2.<b>Nama Badan Hukum</b> : diisi lengkap, jangan disingkat, kecuali melebihi 50 karakter. Untuk PTN nama Badan Hukum diisi dengan Nama Perguruan Tinggi;\r\n3.<b>Tanggal Awal Berdiri</b> : diisi dengan tanggal awal pendirian Badan Hukum. Untuk PTN diisi S. K. Pendirian dari Pemerintah (Keppres/Kepmen/Dikti);\r\n4.<b>Alamat</b> : diisi dengan alamat lengkap\r\n5.<b>Alamat</b> (2) : gunakan bila perlu;\r\n6.<b>Kota</b> : sudah jelas \r\n7.<b>Kode Pos</b> : diisi dengan kode pos kota; \r\n8.<b>Telepon</b> : diisi dengan format: kode area + nomor telepon, contoh: 022-551234;\r\n9.<b>Faks</b> : diisi dengan format: kode area + nomor telepon, contoh: 022-551234;\r\n10.<b>Nomor Akta Terakhir</b> : diisi dengan nomor Akta yang terakhir, kecuali memang tidak ada perubahan Akta sejak didirikan pertama kali;\r\n11.<b>Tanggal Akta Terakhir</b> : sudah jelas\r\n12.<b>Nomor Pengesahan</b> : diisi dengan nomor pengesahan dari Pengadilan Negeri atau Lembar Berita Negara, bila ada;\r\n13.<b>Tanggal Pengesahan</b> : sudah jelas\r\n14.<b>Email</b> : sudah jelas;\r\n15.<b>Home Page</b> : sudah jelas.\r\n\r\n<b>Simpan</b> : untuk proses simpan Data Badan Hukum.\r\n<b>Reset</b> : reset\r\n<b>Cetak</b> : Cetak Data Badan Hukum\r\n";
$arrayhelp[pt] = "\r\nFasilitas ini digunakan untuk entri Data PT (MSPTI)\r\n\r\n1. <b>Kode Badan Hukum</b> : diisi Kode Badan Hukum. Kode Badan Hukum adalah Kode PT ditambah angka 1 didepannya; \r\n2. <b>Kode PT</b> : diisi Kode PT; \r\n3. <b>Nama PT</b> : diisi lengkap, jangan disingkat, kecuali melebihi 50 karakter. Singkatan menggunakan standar yang umum dipakai, seperti: IKIP, STIE, STIKes, dll. Universitas dan Institut tidak disingkat.\r\n4. <b>Tanggal Awal Berdiri</b> : diisi tanggal awal pendirian Perguruan Tinggi, sering terjadi tanggal awal pendirian Perguruan Tinggi sama dengan tanggal awal pendirian Badan Hukum.\r\n5. <b>Alamat</b> : diisi alamat lengkap\r\n6. <b>Alamat (2)</b> : gunakan bila perlu;\r\n7. <b>Kota</b> : sudah jelas \r\n8. <b>Kode Pos</b> : diisi kode pos kota; \r\n9. <b>Telepon</b> : diisi dengan format: kode area + nomor telepon, contoh: 022-551234;\r\n10. <b>Faks</b> : diisi dengan format: kode area + nomor telepon, contoh: 022-551234;\r\n11. <b>Nomor Akta / S.K. Pendirian</b> : diisi nomor Akta atau S.K. Pendirian Perguruan Tinggi;\r\n12. <b>Tanggal Akta / S.K.</b> : sesuai dengan tanggal (perubahan) Akta yang terakhir;\r\n13. <b>Email</b> : sudah jelas;\r\n14. <b>Home Page</b> : sudah jelas.\r\n\r\n<b>Simpan</b> : untuk proses simpan Data PT.\r\n<b>Reset</b> : reset\r\n<b>Cetak</b> : Cetak Data PT\r\n";
$help_koleksiprodi = "Fasilitas ini digunakan untuk melihat data Program Studi yang berpotensi tidak valid saat dikonversi ke DIKTI. \r\n \r\n  Pemeriksaan dilakukan berdasarkan data referensi yang ada di tabel MSPST dan TBPST. Data Program Studi yang tidak terdaftar di MSPST dan TBPST, akan dianggap tidak valid.\r\n \r\n  Silakan periksa keterangan dari daftar Program Studi yang ada di bawah ini dan lakukan penghapusan data jika data Program Studi tsb benar2 tidak valid dan tidak diperlukan sama sekali";
$arrayhelp[tambahprodi] = "\r\nFasilitas ini digunakan untuk entri Data Program Studi (MSPST)\r\n <ol>\r\n <li><b>Kode Program Studi</b> : diisi Kode Program Studi, sesuai dengan TBPST</li>\r\n <li><b>Fakultas / Jurusan</b> : dipilih Fakultas/Jurusan Program Studi ybs</li>\r\n <li><b>Nama Program Studi</b> : diisi nama program studi yang digunakan oleh PT ybs</li>\r\n <li><b>Jenjang Program Studi</b> : diisi dari pilihan yang ada, sesuai dengan TBPST</li>\r\n <li><b>Jumlah SKS Minimum</b> : jumlah kredit yang ditentukan untuk lulus program studi ybs.</li>\r\n <li><b>Jenis Program Studi</b> : diisi dari pilihan yang ada</li> \r\n <li><b>NIDN Ketua</b> : diisi NIDN Ketua Program Studi. Bila suatu Fakultas hanya terdiri dari satu program studi dan tidak ada jabatan Ketua Program Studi maka diisi NIDN Dekan</li>\r\n <li><b>Nama Ketua</b> : diisi nama Ketua Program Studi. Bila suatu Fakultas hanya terdiri dari satu program studi dan tidak ada jabatan Ketua Program Studi maka diisi nama Dekan</li>\r\n <li><b>Alamat</b> : diisi alamat program studi</li>\r\n <li><b>Gelar Kelulusan</b> : diisi gelar kelulusan</li>\r\n <li><b>Kode PT</b> : sudah jelas</li>\r\n <li><b>Kode Program Studi</b> : diisi Kode Program Studi, sesuai dengan TBPST (gunakan pop up Daftar Prodi untuk membantu mencari Kode Prodi yang ada pada TBPST)</li>\r\n <li><b>Tanggal Awal Berdiri</b> : diisi tanggal awal pendirian program studi tersebut</li>\r\n <li><b>Semester Awal Mulai Lapor</b> :\r\n <li><b>Status</b> : diisi Aktif, Hapus bila sudah “tutup”, atau Non aktif bila tidak beroperasi sementara</li>\r\n <li><b>Mulai Semester</b> : diisi bila status Hapus atau Non aktif, yaitu menyatakan mulai semester kapan program studi tersebut ditutup atau non aktif</li>\r\n <li><b>Email</b> : sudah jelas</li>\r\n <li><b>No. SK Terakhir</b> : nomor S.K. Ijin Penyelenggaraan program studi yang terakhir</li>\r\n <li><b>Tanggal SK Terakhir Dikti</b> : tanggal  S.K. Ijin Penyelenggaraan program studi yang terakhir</li>\r\n <li><b>Tanggal Berakhir SK</b> : tanggal akhir berlakunya S.K.</li>\r\n <li><b>No. SK Akreditasi BAN-PT Terakhir</b> : nomor S.K. Akreditasi BAN-PT</li>\r\n <li><b>Tanggal SK Akreditasi</b> : tanggal S.K. Akreditasi BAN-PT</li>\r\n <li><b>Tanggal Berakhir SK Akreditasi</b> : tanggal akhir berlakunya S.K. Akreditasi BAN-PT</li>\r\n <li><b>Status Akreditasi</b> : diisi status Akreditasi BAN-PT</li>\r\n <li><b>Frekuensi Pemutakhiran Kurikulum</b> : diisi dari pilihan yg ada</li>\r\n <li><b>Pelaksanaan Pemutakhiran Kurikulum</b> : diisi dari pilihan yang ada</li>\r\n <li><b>Telepon Ketua Program Studi</b> : diisi nomor telepon Ketua Program Studi</li>\r\n <li><b>Telepon Program Studi</b> : diisi nomor telepon pada Program Studi</li>\r\n <li><b>Faks Program Studi</b> : diisi nomor faksimil pada Program Studi</li>\r\n <li><b>Nama Operator</b> : diisi nama Operator Program Studi</li>\r\n <li><b>Telepon Operator</b> : diisi nomor telepon Operator Program Studi</li>\r\n</ol>\r\n";
$arrayhelp[cariprodi] = "\r\nFasilitas ini digunakan untuk lihat, cari, update, hapus dan cetak Data Program Studi. Pencarian dapat menggunakan filter yang ada untuk proses pencarian yang lebih spesifik. \r\n\r\n<b>Tampilkan</b> : mulai proses pencarian \r\n";
$arrayhelp[hasilprodi] = "\r\nFasilitas ini digunakan untuk update, hapus dan cetak Data Program Studi.\r\n\r\n<b>Cetak</b> : untuk proses cetak Data Program Studi hasil pencarian\r\n<b>Cetak Data Dikti</b> : untuk proses cetak Data Dikti Program Studi hasil pencarian\r\n".IKONHAPUS." : hapus Data Jurusan\r\n".IKONUPDATE." : update Data Jurusan\r\n";
$arrayhelp[updateprodi] = "\r\nFasilitas ini digunakan untuk edit dan update Data Program Studi dan entri Data Kegiatan Perkuliahan.\r\n\r\n<b>Data Kegiatan Perkuliahan</b>\r\n<b>Semester/Tahun Pelaporan</b> : diisi sesuai data yang akan di-entri\r\n<b>Lanjutkan</b> : untuk proses entri Data Kegiatan Perkuliahan\r\n\r\n<b>Update</b> : untuk proses update Data Program Studi\r\n<b>Reset</b> : reset\r\n";
$arrayhelp[tambahfakultas] = "\r\nFasilitas ini digunakan untuk entri <b>Data Fakultas (MSFAK)</b>\r\n\r\n1. <b>Kode Fakultas</b> : diisi Kode Fakultas (numeric);\r\n2. <b>Nama Fakultas</b> : diisi lengkap, jangan disingkat;\r\n3. <b>NIP Dekan/Pimpinan</b> : diisi NIP Dekan/Pimpinan;\r\n4. <b>Nama Dekan/Pimpinan</b> : diisi nama Dekan/Pimpinan;\r\n\r\n<b>Tambah</b> : untuk proses tambah dan simpan Data Fakultas\r\n<b>Reset</b> : reset\r\n";
$arrayhelp[hasilfakultas] = "\r\nFasilitas ini digunakan untuk update, hapus atau cetak <b>Data Fakultas (MSFAK)</b>\r\n\r\n<b>Cetak</b> : untuk proses cetak Data Fakultas hasil pencarian\r\n".IKONHAPUS." : hapus Data Fakultas\r\n".IKONUPDATE." : update Data Fakultas";
$arrayhelp[updatefakultas] = "\r\nFasilitas ini digunakan untuk edit dan update <b>Data Fakultas (MSFAK)</b>\r\n\r\n<b>Update</b> : untuk proses update Data Fakultas\r\n<b>Reset</b> : reset\r\n";
$arrayhelp[tambahjurusan] = "\r\nFasilitas ini digunakan untuk entri Data Jurusan \r\n\r\n1. <b>Fakultas</b> : pilih Fakultas dari Jurusan yang akan ditambahkan;\r\n2. <b>Kode Jurusan</b> : diisi Kode Jurusan (numeric);\r\n3. <b>Nama Jurusan</b> : diisi lengkap, jangan disingkat;\r\n4. <b>NIP Ketua</b> : diisi NIP Ketua Jurusan;\r\n5. <b>Nama Ketua</b> : diisi Nama Ketua Jurusan\r\n6. <b>Alamat Jurusan</b> : sudah jelas;\r\n\r\n<b>Tambah</b> : untuk proses tambah dan simpan Data Jurusan\r\n<b>Reset</b> : reset";
$arrayhelp[carijurusan] = "\r\nFasilitas ini digunakan untuk lihat, cari, update, hapus dan cetak Data Jurusan. Pencarian dapat menggunakan filter yang ada untuk proses pencarian yang lebih spesifik. \r\n\r\n<b>Tampilkan</b> : proses pencarian ";
$arrayhelp[hasiljurusan] = "\r\nFasilitas ini digunakan untuk update, hapus atau cetak <b>Data Jurusan</b>\r\n\r\n<b>Cetak</b> : untuk proses cetak Data Jurusan hasil pencarian\r\n".IKONHAPUS." : hapus Data Jurusan\r\n".IKONUPDATE." : update Data Jurusan";
$arrayhelp[updatejurusan] = "\r\nFasilitas ini digunakan untuk edit dan update <b>Data Jurusan</b>\r\n\r\n<b>Update</b> : untuk proses update Data Jurusan\r\n<b>Reset</b> : reset\r\n";
?>
